version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_ktor
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ktor_db
      MYSQL_USER: ktor_user
      MYSQL_PASSWORD: ktor_password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ktor
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
